version: "3"
services:
  node-app:
    build: .
    ports: 
      - "3000:3000"
      - "4000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5000
    # env_file:
    #  - ./.env